language: node_js
node_js:
  - 14.16.0
install:
  - npm install
  - npm install -g typescript
script:
  - npm run build
branches:
  only:
    - main
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
